<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FieldManagementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $fields = [
            // Customer Basics - System Fields (Required, Cannot be edited/deleted)
            [
                'field_key' => 'full_name',
                'label' => 'Full Name',
                'input_type' => 'text',
                'placeholder' => 'Enter full name',
                'is_required' => true,
                'is_visible' => true,
                'sort_order' => 1,
                'field_group' => 'basic_info',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => 'required|max:255',
                'help_text' => null,
                'is_active' => true,
                'is_system' => true,
            ],
            [
                'field_key' => 'phone',
                'label' => 'Phone Number',
                'input_type' => 'tel',
                'placeholder' => 'Enter phone number',
                'is_required' => true,
                'is_visible' => true,
                'sort_order' => 2,
                'field_group' => 'basic_info',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => 'required|max:20',
                'help_text' => null,
                'is_active' => true,
                'is_system' => true,
            ],
            [
                'field_key' => 'alternate_phone',
                'label' => 'Alternate Phone',
                'input_type' => 'tel',
                'placeholder' => 'Enter alternate phone number',
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 3,
                'field_group' => 'basic_info',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => 'max:20',
                'help_text' => null,
                'is_active' => true,
            ],
            [
                'field_key' => 'email',
                'label' => 'Email Address',
                'input_type' => 'email',
                'placeholder' => 'Enter email address',
                'is_required' => true,
                'is_visible' => true,
                'sort_order' => 4,
                'field_group' => 'basic_info',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => 'required|email|max:255|unique:customers,email',
                'help_text' => null,
                'is_active' => true,
                'is_system' => true,
            ],
            [
                'field_key' => 'date_of_birth',
                'label' => 'Date of Birth',
                'input_type' => 'date',
                'placeholder' => null,
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 5,
                'field_group' => 'basic_info',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => null,
                'help_text' => null,
                'is_active' => true,
            ],
            [
                'field_key' => 'gender',
                'label' => 'Gender',
                'input_type' => 'select',
                'placeholder' => null,
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 6,
                'field_group' => 'basic_info',
                'options' => [
                    ['value' => 'male', 'label' => 'Male'],
                    ['value' => 'female', 'label' => 'Female'],
                    ['value' => 'other', 'label' => 'Other'],
                ],
                'conditional_rules' => null,
                'validation_rules' => null,
                'help_text' => null,
                'is_active' => true,
            ],
            
            // Account Credentials - System Fields (Required for login/register)
            [
                'field_key' => 'password',
                'label' => 'Password',
                'input_type' => 'password',
                'placeholder' => 'Enter password',
                'is_required' => true,
                'is_visible' => true,
                'sort_order' => 10,
                'field_group' => 'credentials',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => 'min:8',
                'help_text' => 'Minimum 8 characters',
                'is_active' => true,
                'is_system' => true,
            ],
            [
                'field_key' => 'password_confirmation',
                'label' => 'Confirm Password',
                'input_type' => 'password',
                'placeholder' => 'Confirm password',
                'is_required' => true,
                'is_visible' => true,
                'sort_order' => 11,
                'field_group' => 'credentials',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => 'min:8',
                'help_text' => null,
                'is_active' => true,
                'is_system' => true,
            ],
            
            // Address Details - System Fields (Required, Cannot be edited/deleted)
            // Order: Address Line 1 -> Address Line 2 -> Landmark -> Pincode -> Country -> State -> City -> Address Type -> Delivery Instructions
            [
                'field_key' => 'address_line1',
                'label' => 'Address Line 1',
                'input_type' => 'text',
                'placeholder' => 'House / Flat / Building / Street',
                'is_required' => true,
                'is_visible' => true,
                'sort_order' => 21,
                'field_group' => 'address',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => 'required|max:255',
                'help_text' => null,
                'is_active' => true,
                'is_system' => true,
            ],
            [
                'field_key' => 'address_line2',
                'label' => 'Address Line 2',
                'input_type' => 'text',
                'placeholder' => 'Area / Locality (optional, not mandatory)',
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 22,
                'field_group' => 'address',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => 'max:255',
                'help_text' => null,
                'is_active' => true,
                'is_system' => true,
            ],
            [
                'field_key' => 'landmark',
                'label' => 'Landmark',
                'input_type' => 'text',
                'placeholder' => 'Enter landmark',
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 23,
                'field_group' => 'address',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => 'max:255',
                'help_text' => null,
                'is_active' => true,
                'is_system' => true,
            ],
            [
                'field_key' => 'pincode',
                'label' => 'Pincode / ZIP Code',
                'input_type' => 'text',
                'placeholder' => 'Enter pincode (triggers auto-fill for City & State)',
                'is_required' => true,
                'is_visible' => true,
                'sort_order' => 24,
                'field_group' => 'address',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => 'required|max:10',
                'help_text' => '→ Trigger auto-fill for City & State',
                'is_active' => true,
                'is_system' => true,
            ],
            [
                'field_key' => 'country',
                'label' => 'Country',
                'input_type' => 'select',
                'placeholder' => 'Defaulted, usually locked',
                'is_required' => true,
                'is_visible' => true,
                'sort_order' => 25,
                'field_group' => 'address',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => 'required',
                'help_text' => null,
                'is_active' => true,
                'is_system' => true,
            ],
            [
                'field_key' => 'state',
                'label' => 'State',
                'input_type' => 'select',
                'placeholder' => 'Select State',
                'is_required' => true,
                'is_visible' => true,
                'sort_order' => 26,
                'field_group' => 'address',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => 'required|max:255',
                'help_text' => null,
                'is_active' => true,
                'is_system' => true,
            ],
            [
                'field_key' => 'city',
                'label' => 'City',
                'input_type' => 'select',
                'placeholder' => 'Auto-filled but editable',
                'is_required' => true,
                'is_visible' => true,
                'sort_order' => 27,
                'field_group' => 'address',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => 'required|max:255',
                'help_text' => 'Auto-filled but editable',
                'is_active' => true,
                'is_system' => true,
            ],
            [
                'field_key' => 'address_type',
                'label' => 'Address Type',
                'input_type' => 'select',
                'placeholder' => null,
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 28,
                'field_group' => 'address',
                'options' => [
                    ['value' => 'home', 'label' => 'Home'],
                    ['value' => 'office', 'label' => 'Work'],
                    ['value' => 'other', 'label' => 'Other'],
                ],
                'conditional_rules' => null,
                'validation_rules' => null,
                'help_text' => null,
                'is_active' => true,
                'is_system' => true,
            ],
            [
                'field_key' => 'delivery_instructions',
                'label' => 'Delivery Instructions',
                'input_type' => 'textarea',
                'placeholder' => 'Enter delivery instructions (optional)',
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 29,
                'field_group' => 'address',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => null,
                'help_text' => 'Optional',
                'is_active' => true,
                'is_system' => true,
            ],
            
            // Business Information (conditional)
            [
                'field_key' => 'business_type',
                'label' => 'Business Type',
                'input_type' => 'select',
                'placeholder' => null,
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 30,
                'field_group' => 'business',
                'options' => [
                    ['value' => 'sole_proprietorship', 'label' => 'Sole Proprietorship'],
                    ['value' => 'partnership', 'label' => 'Partnership'],
                    ['value' => 'llc', 'label' => 'LLC'],
                    ['value' => 'corporation', 'label' => 'Corporation'],
                ],
                'conditional_rules' => [
                    'depends_on' => 'address_type',
                    'show_when' => 'office',
                ],
                'validation_rules' => null,
                'help_text' => null,
                'is_active' => true,
            ],
            [
                'field_key' => 'company_name',
                'label' => 'Company Name',
                'input_type' => 'text',
                'placeholder' => 'Enter company name',
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 31,
                'field_group' => 'business',
                'options' => null,
                'conditional_rules' => [
                    'depends_on' => 'address_type',
                    'show_when' => 'office',
                ],
                'validation_rules' => 'max:255',
                'help_text' => null,
                'is_active' => true,
            ],
            [
                'field_key' => 'gstin',
                'label' => 'GSTIN / Tax ID',
                'input_type' => 'text',
                'placeholder' => 'Enter GSTIN or Tax ID',
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 32,
                'field_group' => 'business',
                'options' => null,
                'conditional_rules' => [
                    'depends_on' => 'address_type',
                    'show_when' => 'office',
                ],
                'validation_rules' => 'max:50',
                'help_text' => null,
                'is_active' => true,
            ],
            
            // Preferences
            [
                'field_key' => 'preferred_contact_method',
                'label' => 'Preferred Contact Method',
                'input_type' => 'select',
                'placeholder' => null,
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 40,
                'field_group' => 'preferences',
                'options' => [
                    ['value' => 'call', 'label' => 'Call'],
                    ['value' => 'sms', 'label' => 'SMS'],
                    ['value' => 'whatsapp', 'label' => 'WhatsApp'],
                    ['value' => 'email', 'label' => 'Email'],
                ],
                'conditional_rules' => null,
                'validation_rules' => null,
                'help_text' => null,
                'is_active' => true,
            ],
            [
                'field_key' => 'preferred_payment_method',
                'label' => 'Preferred Payment Method',
                'input_type' => 'select',
                'placeholder' => null,
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 41,
                'field_group' => 'preferences',
                'options' => [
                    ['value' => 'cash', 'label' => 'Cash'],
                    ['value' => 'card', 'label' => 'Card'],
                    ['value' => 'upi', 'label' => 'UPI'],
                    ['value' => 'netbanking', 'label' => 'Net Banking'],
                ],
                'conditional_rules' => null,
                'validation_rules' => null,
                'help_text' => null,
                'is_active' => true,
            ],
            [
                'field_key' => 'preferred_delivery_slot',
                'label' => 'Preferred Delivery Slot',
                'input_type' => 'select',
                'placeholder' => null,
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 42,
                'field_group' => 'preferences',
                'options' => [
                    ['value' => 'morning', 'label' => 'Morning (9 AM - 12 PM)'],
                    ['value' => 'afternoon', 'label' => 'Afternoon (12 PM - 5 PM)'],
                    ['value' => 'evening', 'label' => 'Evening (5 PM - 9 PM)'],
                ],
                'conditional_rules' => null,
                'validation_rules' => null,
                'help_text' => null,
                'is_active' => true,
            ],
            
            // Quality-of-Life Fields
            [
                'field_key' => 'profile_image',
                'label' => 'Profile Image',
                'input_type' => 'file',
                'placeholder' => null,
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 50,
                'field_group' => 'qol',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => 'image|mimes:jpeg,png,jpg,gif|max:2048',
                'help_text' => 'Recommended size: 400x400px (Max: 2MB)',
                'is_active' => true,
            ],
            [
                'field_key' => 'newsletter_opt_in',
                'label' => 'Newsletter Opt-in',
                'input_type' => 'checkbox',
                'placeholder' => null,
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 51,
                'field_group' => 'qol',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => null,
                'help_text' => 'Subscribe to our newsletter for updates and offers',
                'is_active' => true,
            ],
            
            // Internal Use (hidden from customer but available in admin)
            [
                'field_key' => 'notes',
                'label' => 'Notes',
                'input_type' => 'textarea',
                'placeholder' => 'Enter internal notes',
                'is_required' => false,
                'is_visible' => false,
                'sort_order' => 62,
                'field_group' => 'internal',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => null,
                'help_text' => 'Internal notes about the customer',
                'is_active' => true,
            ],
            
            // Other Group Fields
            [
                'field_key' => 'referral_code',
                'label' => 'Referral Code',
                'input_type' => 'text',
                'placeholder' => 'Enter referral code',
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 70,
                'field_group' => 'other',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => 'max:50',
                'help_text' => 'Referral code if customer was referred by someone',
                'is_active' => true,
            ],
            [
                'field_key' => 'customer_type',
                'label' => 'Customer Type',
                'input_type' => 'select',
                'placeholder' => null,
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 71,
                'field_group' => 'other',
                'options' => [
                    ['value' => 'retail', 'label' => 'Retail'],
                    ['value' => 'wholesale', 'label' => 'Wholesale'],
                    ['value' => 'corporate', 'label' => 'Corporate'],
                    ['value' => 'reseller', 'label' => 'Reseller'],
                ],
                'conditional_rules' => null,
                'validation_rules' => null,
                'help_text' => 'Type of customer relationship',
                'is_active' => true,
            ],
            [
                'field_key' => 'payment_terms',
                'label' => 'Payment Terms',
                'input_type' => 'select',
                'placeholder' => null,
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 73,
                'field_group' => 'other',
                'options' => [
                    ['value' => 'cod', 'label' => 'Cash on Delivery'],
                    ['value' => 'net_15', 'label' => 'Net 15'],
                    ['value' => 'net_30', 'label' => 'Net 30'],
                    ['value' => 'net_45', 'label' => 'Net 45'],
                    ['value' => 'net_60', 'label' => 'Net 60'],
                    ['value' => 'prepaid', 'label' => 'Prepaid'],
                ],
                'conditional_rules' => null,
                'validation_rules' => null,
                'help_text' => 'Payment terms for the customer',
                'is_active' => true,
            ],
            [
                'field_key' => 'tax_exempt',
                'label' => 'Tax Exempt',
                'input_type' => 'checkbox',
                'placeholder' => null,
                'is_required' => false,
                'is_visible' => true,
                'sort_order' => 74,
                'field_group' => 'other',
                'options' => null,
                'conditional_rules' => null,
                'validation_rules' => null,
                'help_text' => 'Check if customer is tax exempt',
                'is_active' => true,
            ],
        ];

            foreach ($fields as $field) {
                $fieldData = $field;
                // Convert arrays to JSON strings
                if (isset($fieldData['options']) && is_array($fieldData['options'])) {
                    $fieldData['options'] = json_encode($fieldData['options']);
                }
                if (isset($fieldData['conditional_rules']) && is_array($fieldData['conditional_rules'])) {
                    $fieldData['conditional_rules'] = json_encode($fieldData['conditional_rules']);
                }
                
                // Use updateOrInsert to ensure field is created/updated
                DB::table('field_management_fields')->updateOrInsert(
                    ['field_key' => $fieldData['field_key']], // Match condition
                    array_merge($fieldData, [
                        'created_at' => DB::raw('COALESCE(created_at, NOW())'), // Preserve existing created_at or set new
                        'updated_at' => now(),
                    ])
                );
            }
    }
}
